### ISSUE TITLE
empty mod

### ISSUE THREAD

**Issue by MK-HATERS** [63OR63/zonepaq#1]
using mod manager and launching this through it, i get an error for merging, says empty file no matter which ones i analyze and merge

**Comment by 63OR63** [comment]
Please run version 1.0.2 or later. It will generate logs in `logs/zonepaq.log`. Share the logs here.

**Comment by 63OR63** [comment]
I'm glad you resolved your issue, though running from uncompiled version should work too, and it's also faster with calls to repak.
