### ISSUE TITLE
Resolve Conflics with 1 PAK and Vanilla Files

### ISSUE THREAD

**Issue by Joaoha** [63OR63/zonepaq#4]
### Describe the bug

Thanks for your tool it's really good. 
I am able to compare 2 pak files with the vanilla PAKs, but I I select only 1 pak file and run analize it always says Numeber of files without conflicts: (whatever Number)

### To Reproduce

1. Go to Resolve Conflicts
2. Click on Resolve Conflicts  -> Select 1 pak file
3. Click Analyze
4. See Results (Always displays no conflitcs.

### Expected behavior

I would expect one could compare 1 mod with the Vanilla Files. Could be good for mod development. Or making some custom changes...

### Environment Details

Please complete the following information:

- **ZonePaq Version**: 1.3.1
- **Launch Type**: [Compiled]
- **Python Version (if uncompiled)**: [e.g., 3.8]
- **Operating System**: Windows 10]

### Logs

Please, include lines from `logs/zonepaq.log` file in the following code block:

<details><summary>Click to expand</summary><code>logs/zonepaq.log:
...log lines here...
</code></details>

### Screenshots

![image](https://github.com/user-attachments/assets/d52d1894-285c-4f9c-be23-86f4d1bc18fb)

**Comment by 63OR63** [comment]
There’s no issue here. In this context, a *conflict* occurs when the same `.cfg` file exists in multiple `.pak` files. A mod cannot conflict with itself.

However, **you can still compare a single mod with vanilla files**. To do this, uncheck *Ignore files without conflicts*, select the desired `.cfg` files, and click *Process*. Note that the vanilla files must be unpacked and configured in the settings.

The upcoming version 2.0 will include features like automatic installation of required tools, unpacking vanilla files, and retrieving the correct AES key, among other improvements. I’ll also see if I can make this screen more intuitive. I’m aiming to release v2.0 before Christmas, stay tuned.

**Comment by Joaoha** [comment]
You're a legend. Thank you. I knew about the ignore files without conflicts option for packing the merged mods but did not understand it also worked for the comparison. I confirm it works. Cheers
